spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
zuul:
  retryable: true
#y有默认配置 
#ribbon:
#  ConnectTimeout: 1000
#  ReadTimeout: 1000
#  MaxAutoRetriesNextServer: 1
#  MaxAutoRetries: 1
   
hystrix: #熔断
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
 #暴露 hystrix.stream 监控端点           
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream         



         